export { resolveSuccession } from './constitution';
export type {
  BindingSupportInput,
  CandidateId,
  CandidateTally,
  CandidateValidationReconstruction,
  ConstitutionReason,
  ConstitutionReasonCode,
  CouncilBallotReconstruction,
  CouncilVoteRecord,
  CouncilVoterInput,
  DecisiveRule,
  DeclarationPrecedence,
  EliminationTieCriterion,
  EvaluatedVote,
  FinalTieCriterion,
  GreyfenManualVoteInput,
  GreyfenVoteDecision,
  MilitaryAcclamationInput,
  ReleasedSupportContext,
  SuccessionCandidateInput,
  SuccessionConstitutionInput,
  SuccessionFact,
  SuccessionReason,
  SuccessionReconstruction,
  SuccessionResolution,
  SuppliedSuccessionReason,
  TieBreakStep,
  TieBreakValue,
  UnboundVoteContext,
  UnboundVoteEvaluator,
  VoteSource,
} from './types';
