allowBuilds:
  esbuild: true
peerDependencyRules:
  allowedVersions:
    '@docsearch/react>@types/react': '19'
    '@docsearch/react>react': '19'
    '@docsearch/react>react-dom': '19'
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.5.9'
  - '@storybook/builder-vite@10.5.9'
  - '@storybook/csf-plugin@10.5.9'
  - '@storybook/react-dom-shim@10.5.9'
  - '@storybook/react-vite@10.5.9'
  - '@storybook/react@10.5.9'
  - '@vitest/coverage-v8@4.1.11'
  - '@vitest/expect@4.1.11'
  - '@vitest/mocker@4.1.11'
  - '@vitest/pretty-format@4.1.11'
  - '@vitest/runner@4.1.11'
  - '@vitest/snapshot@4.1.11'
  - '@vitest/spy@4.1.11'
  - '@vitest/utils@4.1.11'
  - storybook@10.5.9
  - vitest@4.1.11
  - '@storybook/addon-vitest@10.5.9'
  - '@vitest/browser-playwright@4.1.11'
  - '@vitest/browser@4.1.11'
