/** Lower values resolve first at an identical simulation timestamp. */
export const DAWN_PRIORITY = {
  PLAYER_ORDERS_AND_AI_INTENTS: 100,
  BATTLES_OCCUPATIONS_AND_PUBLIC_FALLOUT: 200,
  AGREEMENTS_SUPPORT_CHURCH_AND_CONTROL: 300,
  EXPIRY_DECAY_INCOME_AND_RECOVERY: 400,
  HEALTH_PHASE_TRANSITION: 500,
  KINGS_DEATH_CHECK: 600,
  AMBIENT_EVENT_WINDOW: 700,
  AI_INTENT_SELECTION: 800,
  AUTOSAVE_AND_CHRONICLE: 900,
} as const;

export type DawnPriority = (typeof DAWN_PRIORITY)[keyof typeof DAWN_PRIORITY];
