import type { ActionDefinition, StructuredEffect } from './schemas';

const label = (id: string) => `content.label.${id}`;
const explanation = (id: string) => `content.explanation.${id}`;
const allPhases = ['stable', 'ailing', 'gravely-ill', 'deathbed'] as const;
const successionPhases = ['ailing', 'gravely-ill', 'deathbed'] as const;
const preparationPhases = ['stable', 'ailing', 'gravely-ill'] as const;

const previewFields = [
  'preview.duration',
  'preview.start-cost',
  'preview.acceptance-collateral',
  'preview.troops-locked',
  'preview.visibility',
  'preview.known-effects',
  'preview.cancellation',
  'preview.invalidation',
  'preview.intentional-unknowns',
] as const;

type ActionInput = Omit<
  ActionDefinition,
  'labelKey' | 'explanationKey' | 'chronicleStartKey' | 'chronicleResultKey' | 'previewFieldKeys'
>;

const action = (definition: ActionInput): ActionDefinition => ({
  ...definition,
  labelKey: label(`action-${definition.id}`),
  explanationKey: explanation(`action-${definition.id}`),
  previewFieldKeys: [...previewFields],
  chronicleStartKey: `chronicle.action.${definition.id}.start`,
  chronicleResultKey: `chronicle.action.${definition.id}.result`,
});

const repeat = (
  mode: ActionDefinition['repeatRule']['mode'],
  windowDays: number | null,
  maxFullEffects: number | null,
  id: string,
): ActionDefinition['repeatRule'] => ({
  mode,
  windowDays,
  maxFullEffects,
  explanationKey: explanation(`repeat-${id}`),
});

const costOption = (id: string, gold: number, influence = 0, troopMinimum = 0) => ({
  id,
  gold,
  influence,
  troopMinimum,
  explanationKey: explanation(`cost-${id}`),
});

export const actions = [
  action({
    id: 'send-gift',
    familyId: 'gift',
    displayOrder: 1,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['lord'],
    duration: { days: 1, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 20, influence: 0, logisticsGold: 0 },
    costOptions: [
      costOption('gift-small', 20),
      costOption('gift-medium', 40),
      costOption('gift-large', 80),
    ],
    acceptanceCollateralTiming: 'none',
    visibility: 'private-to-parties',
    repeatRule: {
      ...repeat('diminishing', 14, 1, 'gift'),
      effectMultipliers: [1, 0.5, 0],
      refuseAfterUses: 2,
      chargeOnRefusal: false,
    },
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'target-unavailable-fail',
    resultEffectIds: ['adjust-relationship'],
    aiPermissionTags: ['relationship-cultivation'],
    chronicleCategoryId: 'court',
  }),
  action({
    id: 'offer-bargain',
    familyId: 'offer-bargain',
    displayOrder: 2,
    kind: 'base',
    legalPhaseIds: [...successionPhases],
    targetKinds: ['kingmaker'],
    duration: { days: 2, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 0, influence: 8, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'acceptance',
    visibility: 'private-to-parties',
    repeatRule: repeat('contextual', null, null, 'bargain'),
    cancellationPolicyId: 'negotiation-influence-not-refunded',
    invalidationPolicyId: 'collateral-untouched-if-target-unavailable',
    resultEffectIds: ['lock-gold', 'lock-troops', 'reserve-office', 'enact-policy'],
    aiPermissionTags: ['succession', 'kingmaker'],
    chronicleCategoryId: 'succession',
  }),
  action({
    id: 'request-declaration',
    familyId: 'request-declaration',
    displayOrder: 3,
    kind: 'base',
    legalPhaseIds: [...successionPhases],
    targetKinds: ['lord'],
    duration: { days: 2, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 0, influence: 8, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'private-to-parties',
    repeatRule: repeat('cooldown', 7, 1, 'request-declaration'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'external-loss-minus-two-no-cooldown-premature-minus-four-seven-days',
    resultEffectIds: ['set-support-shock'],
    aiPermissionTags: ['succession', 'pledge-request'],
    chronicleCategoryId: 'succession',
  }),
  action({
    id: 'threaten',
    familyId: 'threaten',
    displayOrder: 4,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['lord'],
    duration: { days: 2, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 0, influence: 12, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'private-to-parties',
    visibilityVariants: [
      {
        ruleId: 'military-or-occupation-leverage',
        visibility: 'public',
        supportLabel: 'under-duress',
      },
      {
        ruleId: 'secret-blackmail-leverage',
        visibility: 'private-to-parties',
        supportLabel: 'pledged',
      },
    ],
    repeatRule: {
      ...repeat('once-per-phase', null, 1, 'threaten'),
      resetRuleIds: ['new-qualifying-leverage-acquired'],
    },
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'leverage-required-at-start-and-resolution',
    resultEffectIds: ['adjust-relationship', 'set-support-shock'],
    aiPermissionTags: ['coercion', 'requires-leverage'],
    chronicleCategoryId: 'succession',
  }),
  action({
    id: 'watch-court',
    familyId: 'spy',
    displayOrder: 5,
    kind: 'variant',
    legalPhaseIds: [...allPhases],
    targetKinds: ['lord'],
    duration: { days: 3, deathbedDays: 3, fixedAtStart: true },
    startCost: { gold: 20, influence: 8, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'hidden',
    repeatRule: repeat('unlimited', null, null, 'watch-court'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'return-current-available-intelligence',
    resultEffectIds: ['reveal-intelligence'],
    intelligenceFreshDays: 7,
    aiPermissionTags: ['intelligence', 'legal-in-deathbed'],
    chronicleCategoryId: 'intelligence',
  }),
  action({
    id: 'find-dirt',
    familyId: 'spy',
    displayOrder: 6,
    kind: 'variant',
    legalPhaseIds: [...preparationPhases],
    targetKinds: ['lord'],
    duration: { days: 5, deathbedDays: 5, fixedAtStart: true },
    startCost: { gold: 30, influence: 12, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'hidden',
    repeatRule: repeat('diminishing', 10, 1, 'find-dirt'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'snapshotted-check-and-lesser-intelligence-fallback',
    resultEffectIds: ['reveal-secret', 'reveal-intelligence'],
    aiPermissionTags: ['intelligence', 'long-preparation'],
    chronicleCategoryId: 'intelligence',
  }),
  action({
    id: 'research-lineage',
    familyId: 'build-claim',
    displayOrder: 7,
    kind: 'variant',
    legalPhaseIds: [...preparationPhases],
    targetKinds: ['none'],
    duration: { days: 6, deathbedDays: 6, fixedAtStart: true },
    startCost: { gold: 35, influence: 12, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'suspected',
    repeatRule: repeat('once-per-run', null, 1, 'research-lineage'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'once-completed-lock',
    resultEffectIds: ['adjust-claim'],
    canonicalResults: [
      { effectId: 'adjust-claim', target: 'player', value: 12, visibility: 'public' },
    ],
    aiPermissionTags: ['claim', 'long-preparation'],
    chronicleCategoryId: 'succession',
  }),
  action({
    id: 'forge-royal-descent',
    familyId: 'build-claim',
    displayOrder: 8,
    kind: 'variant',
    legalPhaseIds: [...preparationPhases],
    targetKinds: ['none'],
    duration: { days: 8, deathbedDays: 8, fixedAtStart: true },
    startCost: { gold: 50, influence: 25, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'hidden',
    repeatRule: repeat('once-per-run', null, 1, 'forge-royal-descent'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'once-completed-lock',
    resultEffectIds: ['adjust-claim', 'create-secret'],
    canonicalResults: [
      { effectId: 'adjust-claim', target: 'player', value: 25, visibility: 'public' },
      {
        effectId: 'create-secret',
        target: 'player',
        referenceId: 'player-forgery-evidence',
        visibility: 'private',
      },
    ],
    aiPermissionTags: ['claim', 'fraud', 'long-preparation'],
    chronicleCategoryId: 'intelligence',
  }),
  action({
    id: 'expose-secret',
    familyId: 'expose-secret',
    displayOrder: 9,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['secret'],
    duration: { days: 2, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 0, influence: 10, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', null, 1, 'expose-secret'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'secret-must-remain-unexposed',
    resultEffectIds: ['adjust-prestige', 'adjust-claim', 'set-support-shock'],
    aiPermissionTags: ['intelligence', 'public-scandal'],
    chronicleCategoryId: 'intelligence',
  }),
  action({
    id: 'invade-territory',
    familyId: 'invade',
    displayOrder: 10,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['territory'],
    duration: { days: 3, deathbedDays: 2, fixedAtStart: true },
    startCost: { gold: 0, influence: 0, logisticsGold: 10 },
    costOptions: [costOption('invasion-minimum', 10, 0, 25)],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('unlimited', null, null, 'invade'),
    cancellationPolicyId: 'troops-return-before-battle-logistics-lost',
    invalidationPolicyId: 'campaign-revalidation-and-explicit-return-travel',
    resultEffectIds: ['adjust-levies', 'adjust-prestige', 'apply-condition'],
    aiPermissionTags: ['war', 'requires-adjacent-base'],
    chronicleCategoryId: 'war',
  }),
  action({
    id: 'raise-taxes',
    familyId: 'raise-taxes',
    displayOrder: 11,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['none'],
    duration: { days: 1, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 0, influence: 0, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', 21, 1, 'raise-taxes'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'greyfen-must-remain-unoccupied',
    resultEffectIds: ['adjust-gold', 'apply-condition', 'remove-condition'],
    resultBranches: [
      {
        id: 'first-unstrained-collection',
        requirementIds: ['greyfen-unoccupied', 'no-tax-strain', 'no-unrest'],
        effects: [
          {
            effectId: 'adjust-gold',
            target: 'player',
            value: 14,
            referenceId: 'days-current-gross-greyfen-income',
            visibility: 'public',
          },
          {
            effectId: 'apply-condition',
            target: 'player',
            referenceId: 'tax-strain',
            durationDays: 21,
            visibility: 'public',
          },
        ],
      },
      {
        id: 'strained-repeat',
        requirementIds: ['greyfen-unoccupied', 'tax-strain-active'],
        effects: [
          {
            effectId: 'adjust-gold',
            target: 'player',
            value: 7,
            referenceId: 'days-current-gross-greyfen-income',
            visibility: 'public',
          },
          {
            effectId: 'remove-condition',
            target: 'player',
            referenceId: 'tax-strain',
            visibility: 'public',
          },
          {
            effectId: 'apply-condition',
            target: 'player',
            referenceId: 'unrest',
            durationDays: 21,
            visibility: 'public',
          },
        ],
      },
    ],
    aiPermissionTags: ['economy', 'greyfen-only'],
    chronicleCategoryId: 'economy',
  }),
  action({
    id: 'hold-court',
    familyId: 'hold-court',
    displayOrder: 12,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['lord'],
    duration: { days: 3, deathbedDays: 2, fixedAtStart: true },
    startCost: { gold: 60, influence: 0, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('diminishing', 21, 1, 'hold-court'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'unavailable-invitees-removed',
    resultEffectIds: ['adjust-prestige', 'adjust-influence', 'adjust-relationship'],
    canonicalResults: [
      { effectId: 'adjust-prestige', target: 'player', value: 8, visibility: 'public' },
      { effectId: 'adjust-influence', target: 'player', value: 10, visibility: 'public' },
      { effectId: 'adjust-relationship', target: 'target', value: 6, visibility: 'parties' },
    ],
    aiPermissionTags: ['court', 'relationship-cultivation'],
    chronicleCategoryId: 'court',
  }),
  action({
    id: 'patronize-church',
    familyId: 'patronize-church',
    displayOrder: 13,
    kind: 'base',
    legalPhaseIds: [...allPhases],
    targetKinds: ['none'],
    duration: { days: 4, deathbedDays: 3, fixedAtStart: true },
    startCost: { gold: 50, influence: 0, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('cooldown', 21, 1, 'patronize-church'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'institutional-benefit-once',
    resultEffectIds: ['adjust-relationship', 'apply-condition'],
    canonicalResults: [
      {
        effectId: 'adjust-relationship',
        target: 'oswin',
        value: 8,
        referenceId: 'first-patronage-only',
        visibility: 'parties',
      },
      {
        effectId: 'apply-condition',
        target: 'player',
        referenceId: 'church-patronage',
        visibility: 'public',
      },
    ],
    aiPermissionTags: ['church', 'legitimacy'],
    chronicleCategoryId: 'church',
  }),
  action({
    id: 'declare-candidacy',
    familyId: null,
    displayOrder: 14,
    kind: 'contextual',
    legalPhaseIds: [...successionPhases],
    targetKinds: ['none'],
    duration: { days: 1, deathbedDays: 1, fixedAtStart: true },
    startCost: { gold: 0, influence: 15, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('once-per-run', null, 1, 'declare-candidacy'),
    cancellationPolicyId: 'irreversible-on-completion',
    invalidationPolicyId: 'phase-and-candidacy-revalidate',
    resultEffectIds: ['declare-candidate', 'adjust-prestige', 'apply-condition'],
    aiPermissionTags: ['succession', 'player-only'],
    chronicleCategoryId: 'succession',
  }),
  action({
    id: 'march-on-capital',
    familyId: null,
    displayOrder: 15,
    kind: 'contextual',
    legalPhaseIds: ['gravely-ill', 'deathbed'],
    targetKinds: ['capital'],
    duration: { days: 3, deathbedDays: 2, fixedAtStart: true },
    durationVariants: [{ ruleId: 'capital-uncontrolled', days: 1 }],
    startCost: { gold: 0, influence: 0, logisticsGold: 10 },
    costOptions: [costOption('capital-attack-minimum', 10, 0, 250)],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', null, null, 'march-on-capital'),
    cancellationPolicyId: 'troops-return-before-battle-logistics-lost',
    invalidationPolicyId: 'capital-controller-revalidation',
    resultEffectIds: ['adjust-levies', 'adjust-prestige', 'apply-condition'],
    aiPermissionTags: ['war', 'declared-claimant', 'capital'],
    chronicleCategoryId: 'war',
  }),
  action({
    id: 'break-agreement',
    familyId: null,
    displayOrder: 16,
    kind: 'reaction',
    legalPhaseIds: [...allPhases],
    targetKinds: ['agreement'],
    duration: { days: 0, deathbedDays: 0, fixedAtStart: true },
    startCost: { gold: 0, influence: 0, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', null, null, 'break-agreement'),
    cancellationPolicyId: 'instant-reaction',
    invalidationPolicyId: 'agreement-must-remain-active',
    resultEffectIds: ['adjust-prestige', 'adjust-relationship', 'apply-condition'],
    aiPermissionTags: ['reaction', 'agreement'],
    chronicleCategoryId: 'succession',
  }),
  action({
    id: 'withdraw-occupation',
    familyId: null,
    displayOrder: 17,
    kind: 'reaction',
    legalPhaseIds: [...allPhases],
    targetKinds: ['territory'],
    duration: { days: 0, deathbedDays: 0, fixedAtStart: true },
    startCost: { gold: 0, influence: 0, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', null, null, 'withdraw-occupation'),
    cancellationPolicyId: 'instant-reaction',
    invalidationPolicyId: 'no-battle-pending-and-one-day-return',
    resultEffectIds: ['remove-condition'],
    aiPermissionTags: ['reaction', 'war'],
    chronicleCategoryId: 'war',
  }),
  action({
    id: 'confess-and-seek-penance',
    familyId: null,
    displayOrder: 18,
    kind: 'contextual',
    legalPhaseIds: [...allPhases],
    targetKinds: ['none'],
    duration: { days: 3, deathbedDays: 3, fixedAtStart: true },
    startCost: { gold: 40, influence: 10, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', null, 1, 'penance'),
    cancellationPolicyId: 'no-refund-after-start',
    invalidationPolicyId: 'requires-exposed-forgery-condemnation',
    resultEffectIds: ['adjust-prestige', 'set-church-state', 'remove-condition'],
    canonicalResults: [
      { effectId: 'adjust-prestige', target: 'player', value: -5, visibility: 'public' },
      {
        effectId: 'set-church-state',
        target: 'church',
        referenceId: 'skeptical',
        visibility: 'public',
      },
      {
        effectId: 'remove-condition',
        target: 'player',
        referenceId: 'forgery-evidence',
        visibility: 'public',
      },
    ],
    aiPermissionTags: ['fraud-repair', 'player-only'],
    chronicleCategoryId: 'church',
  }),
  action({
    id: 'cast-greyfens-vote',
    familyId: null,
    displayOrder: 19,
    kind: 'reaction',
    legalPhaseIds: ['deathbed'],
    targetKinds: ['candidate'],
    duration: { days: 0, deathbedDays: 0, fixedAtStart: true },
    startCost: { gold: 0, influence: 0, logisticsGold: 0 },
    costOptions: [],
    acceptanceCollateralTiming: 'none',
    visibility: 'public',
    repeatRule: repeat('contextual', null, 1, 'cast-greyfens-vote'),
    cancellationPolicyId: 'mandatory-decision',
    invalidationPolicyId: 'remaining-candidates-revalidate',
    resultEffectIds: ['none'],
    aiPermissionTags: ['player-only', 'succession-decision'],
    chronicleCategoryId: 'succession',
  }),
];

const publicEffect = (
  effectId: StructuredEffect['effectId'],
  target: StructuredEffect['target'],
  value?: number,
  referenceId?: string,
): StructuredEffect => ({
  effectId,
  target,
  ...(value === undefined ? {} : { value }),
  ...(referenceId === undefined ? {} : { referenceId }),
  visibility: 'public',
});

const bargainBase = (id: string, lordId: string, displayOrder: number) => ({
  id,
  lordId,
  displayOrder,
  labelKey: label(`bargain-${id}`),
  explanationKey: explanation(`bargain-${id}`),
  negotiationInfluenceCost: 8,
});

export const bargains = [
  {
    ...bargainBase('edric-marshal', 'edric', 1),
    collateralMode: 'all',
    presentCollateral: [],
    reservedFutureOffice: 'marshal',
    proofIds: [
      'edric-major-victory',
      'edric-military-peer',
      'edric-border-aid',
      'edric-capital-control',
    ],
    supportEffect: 'leaning-only',
    incompatibleConditionIds: ['oathbreaker'],
    breachRedLineIds: ['edric-broke-promised-aid'],
    effects: [publicEffect('reserve-office', 'player', undefined, 'marshal')],
  },
  {
    ...bargainBase('edric-border-aid', 'edric', 2),
    collateralMode: 'all',
    presentCollateral: [{ type: 'troop-lock', timing: 'acceptance', amount: 150, durationDays: 7 }],
    proofIds: ['edric-border-aid'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['oathbreaker'],
    breachRedLineIds: ['edric-broke-promised-aid'],
    effects: [publicEffect('lock-troops', 'player', 150, 'seven-days')],
  },
  {
    ...bargainBase('edric-joint-campaign', 'edric', 3),
    collateralMode: 'all',
    presentCollateral: [
      { type: 'troop-lock', timing: 'acceptance', amount: 100 },
      { type: 'shared-risk', timing: 'acceptance', amount: 100 },
    ],
    proofIds: ['edric-border-aid'],
    supportEffect: 'commitment-on-shared-risk',
    incompatibleConditionIds: ['oathbreaker'],
    breachRedLineIds: ['edric-abandoned-shared-war'],
    effects: [publicEffect('lock-troops', 'player', 100, 'joint-campaign')],
  },
  {
    ...bargainBase('ysabel-escrow', 'ysabel', 4),
    collateralMode: 'all',
    presentCollateral: [{ type: 'gold-escrow', timing: 'acceptance', amount: 80 }],
    proofIds: ['ysabel-escrow'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['defaulted-debtor'],
    breachRedLineIds: ['ysabel-bargain-collapse'],
    effects: [publicEffect('lock-gold', 'player', 80, 'ysabel-escrow')],
  },
  {
    ...bargainBase('ysabel-chancellorship', 'ysabel', 5),
    collateralMode: 'all',
    presentCollateral: [
      { type: 'gold-escrow', timing: 'acceptance', amount: 40 },
      { type: 'office-reservation', timing: 'acceptance', officeId: 'chancellor' },
    ],
    reservedFutureOffice: 'chancellor',
    proofIds: [],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['defaulted-debtor'],
    breachRedLineIds: ['ysabel-bargain-collapse'],
    effects: [
      publicEffect('lock-gold', 'player', 40, 'chancellor-budget'),
      publicEffect('reserve-office', 'player', undefined, 'chancellor'),
    ],
  },
  {
    ...bargainBase('ysabel-protection', 'ysabel', 6),
    collateralMode: 'all',
    presentCollateral: [{ type: 'troop-lock', timing: 'acceptance', amount: 100, durationDays: 7 }],
    proofIds: ['ysabel-protection'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['defaulted-debtor'],
    breachRedLineIds: ['ysabel-bargain-collapse'],
    effects: [publicEffect('lock-troops', 'eastvale', 100, 'seven-days')],
  },
  {
    ...bargainBase('oswin-abbey-endowment', 'oswin', 7),
    collateralMode: 'all',
    presentCollateral: [{ type: 'gold-payment', timing: 'acceptance', amount: 60 }],
    proofIds: ['oswin-lawful-legitimacy'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['usurper'],
    breachRedLineIds: ['oswin-sacrilegious-agreement'],
    effects: [
      publicEffect('adjust-gold', 'player', -60, 'abbey-endowment'),
      publicEffect('adjust-relationship', 'oswin', 8, 'first-patronage-only'),
      publicEffect('apply-condition', 'player', undefined, 'church-patronage'),
    ],
  },
  {
    ...bargainBase('oswin-church-immunities', 'oswin', 8),
    collateralMode: 'all',
    presentCollateral: [
      { type: 'policy-concession', timing: 'acceptance', policyId: 'church-immunities' },
      { type: 'completed-action', timing: 'acceptance', requiredActionId: 'patronize-church' },
    ],
    proofIds: ['oswin-lawful-legitimacy'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['usurper'],
    breachRedLineIds: ['oswin-sacrilegious-agreement'],
    effects: [publicEffect('enact-policy', 'player', 0.8, 'church-immunities')],
  },
  {
    ...bargainBase('oswin-renunciation', 'oswin', 9),
    collateralMode: 'all',
    presentCollateral: [{ type: 'public-renunciation', timing: 'acceptance' }],
    proofIds: ['oswin-lawful-legitimacy'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['usurper'],
    breachRedLineIds: ['oswin-sacrilegious-agreement'],
    effects: [publicEffect('set-bargain-progress', 'player', 0, 'named-impious-agreement')],
  },
  {
    ...bargainBase('mara-greyfen-charter', 'mara', 10),
    collateralMode: 'all',
    presentCollateral: [
      { type: 'policy-concession', timing: 'acceptance', policyId: 'greyfen-charter' },
    ],
    proofIds: ['mara-charter'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: ['usurper'],
    breachRedLineIds: ['mara-charter-revoked'],
    effects: [
      publicEffect('enact-policy', 'player', 0.75, 'greyfen-charter'),
      publicEffect('adjust-relationship', 'edric', -4),
      publicEffect('adjust-relationship', 'oswin', -3),
    ],
  },
  {
    ...bargainBase('mara-denounce-central-rule', 'mara', 11),
    collateralMode: 'all',
    presentCollateral: [
      { type: 'policy-concession', timing: 'acceptance', policyId: 'denounce-central-rule' },
    ],
    proofIds: [],
    supportEffect: 'leaning-only',
    incompatibleConditionIds: [],
    breachRedLineIds: ['mara-centralizing-program'],
    effects: [
      publicEffect('adjust-relationship', 'renard', -15),
      publicEffect('adjust-relationship', 'mara', 4),
      publicEffect('adjust-relationship', 'oswin', -3),
      publicEffect('enact-policy', 'player', 1, 'denounce-central-rule'),
    ],
  },
  {
    ...bargainBase('mara-provincial-aid', 'mara', 12),
    collateralMode: 'one-of',
    presentCollateral: [
      { type: 'troop-lock', timing: 'acceptance', amount: 100, durationDays: 5 },
      { type: 'shared-risk', timing: 'acceptance' },
    ],
    proofIds: ['mara-provincial-aid', 'mara-liberation'],
    supportEffect: 'pledge-eligible',
    incompatibleConditionIds: [],
    breachRedLineIds: ['mara-provincial-aid-betrayed'],
    effects: [publicEffect('lock-troops', 'player', 100, 'five-days-or-liberate-westmarch')],
  },
];
