const label = (id: string) => `content.label.${id}`;
const explanation = (id: string) => `content.explanation.${id}`;

const modifier = (id: string, value: number) => ({
  id,
  value,
  explanationKey: explanation(`evaluation-${id}`),
});

export const candidateEvaluations = [
  {
    lordId: 'edric',
    legitimacy: {
      claim: { none: -6, dubious: -3, plausible: 0, strong: 2, excellent: 4, overwhelming: 5 },
      church: { condemned: -4, skeptical: -1, neutral: 0, favorable: 1, endorsed: 2 },
      clamp: [-8, 7],
    },
    desireAndConductClamp: [-25, 25],
    desireAndConduct: [
      modifier('edric-military-below-half', -12),
      modifier('edric-military-half-to-89', -5),
      modifier('edric-military-peer', 8),
      modifier('edric-military-dominant', 5),
      modifier('edric-military-overwhelming', 5),
      modifier('edric-recent-major-victory', 8),
      modifier('edric-recent-major-defeat', -8),
      modifier('edric-fulfilled-border-aid', 10),
      modifier('edric-shared-campaign-victory', 12),
      modifier('edric-capital-held-three-days', 5),
      modifier('edric-abandoned-ally', -15),
      modifier('edric-military-oathbreaker', -20),
    ],
    fear: { low: 0, concern: 3, serious: -8, existential: -20 },
    proofIds: [
      'edric-major-victory',
      'edric-military-peer',
      'edric-border-aid',
      'edric-capital-control',
    ],
    redLineIds: [
      'edric-broke-promised-aid',
      'edric-abandoned-shared-war',
      'edric-northkeep-occupied',
      'edric-destruction-program',
    ],
  },
  {
    lordId: 'ysabel',
    legitimacy: {
      claim: { none: -8, dubious: -4, plausible: 0, strong: 2, excellent: 4, overwhelming: 5 },
      church: { condemned: -5, skeptical: -2, neutral: 0, favorable: 2, endorsed: 4 },
      clamp: [-12, 9],
    },
    desireAndConductClamp: [-25, 25],
    desireAndConduct: [
      modifier('ysabel-capital-control', 4),
      modifier('ysabel-protected-eastvale', 15),
      modifier('ysabel-active-protection', 8),
      modifier('ysabel-recent-major-victory', 4),
      modifier('ysabel-recent-major-defeat', -6),
      modifier('ysabel-public-oathbreaker', -8),
      modifier('ysabel-defaulted-debtor', -25),
      modifier('ysabel-support-collapse-after-risk', -12),
    ],
    fear: { low: 0, concern: 2, serious: -6, existential: -15 },
    fearOverrides: [
      {
        threatBand: 'serious',
        whenRuleId: 'active-protection-benefits-ysabel',
        value: 4,
        mode: 'replace',
      },
    ],
    proofIds: [
      'ysabel-public-support',
      'ysabel-claim-and-church',
      'ysabel-capital-control',
      'ysabel-rival-defeat',
      'ysabel-escrow',
      'ysabel-protection',
    ],
    redLineIds: [
      'ysabel-eastvale-occupied',
      'ysabel-defaulted-debtor',
      'ysabel-network-destroyed',
      'ysabel-bargain-collapse',
    ],
  },
  {
    lordId: 'oswin',
    legitimacy: {
      claim: { none: -15, dubious: -10, plausible: 0, strong: 5, excellent: 8, overwhelming: 10 },
      church: { condemned: 'excluded', skeptical: -5, neutral: 0, favorable: 3, endorsed: 5 },
      clamp: [-20, 15],
    },
    desireAndConductClamp: [-25, 25],
    desireAndConduct: [
      modifier('oswin-patronage-or-endowment', 5),
      modifier('oswin-defended-abbeylands', 10),
      modifier('oswin-funeral', 3),
      modifier('oswin-church-immunities', 8),
      modifier('oswin-lawful-rival-impiety', 5),
      modifier('oswin-broke-peace-ailing', -4),
      modifier('oswin-defied-peace-stable', -8),
      modifier('oswin-usurper', -8),
      modifier('oswin-second-offensive-war', -5),
      modifier('oswin-public-oathbreaker', -8),
    ],
    fear: { low: 0, concern: -2, serious: -8, existential: -15 },
    proofIds: ['oswin-lawful-legitimacy'],
    redLineIds: [
      'oswin-abbeylands-attacked',
      'oswin-unconfessed-forgery',
      'oswin-church-wealth-seized',
      'oswin-sacrilegious-agreement',
      'oswin-public-coercion',
    ],
  },
  {
    lordId: 'mara',
    legitimacy: {
      claim: { none: 3, dubious: 2, plausible: 0, strong: -2, excellent: -4, overwhelming: -6 },
      church: { condemned: 0, skeptical: 1, neutral: 0, favorable: -1, endorsed: -3 },
      clamp: [-9, 4],
    },
    desireAndConductClamp: [-25, 25],
    desireAndConduct: [
      modifier('mara-greyfen-charter', 20),
      modifier('mara-provincial-liberties', 6),
      modifier('mara-denounced-central-rule', 8),
      modifier('mara-fulfilled-provincial-aid', 12),
      modifier('mara-liberated-westmarch', 20),
      modifier('mara-defended-centralization', -12),
      modifier('mara-expanded-royal-tax-levy', -20),
      modifier('mara-seized-capital-from-renard', 3),
      modifier('mara-public-oathbreaker', -10),
    ],
    fear: { low: 0, concern: -2, serious: -10, existential: -20 },
    proofIds: ['mara-charter', 'mara-provincial-aid', 'mara-liberation'],
    redLineIds: [
      'mara-westmarch-occupied',
      'mara-charter-revoked',
      'mara-centralizing-program',
      'mara-provincial-aid-betrayed',
    ],
  },
  {
    lordId: 'renard',
    legitimacy: {
      claim: { none: -10, dubious: -6, plausible: 0, strong: 4, excellent: 7, overwhelming: 9 },
      church: { condemned: -8, skeptical: -3, neutral: 0, favorable: 3, endorsed: 6 },
      clamp: [-18, 15],
    },
    desireAndConductClamp: [-25, 25],
    desireAndConduct: [
      modifier('renard-secret-exposed-by-candidate', -20),
      modifier('renard-southmere-occupied', -25),
      modifier('renard-defeated', -10),
      modifier('renard-southmere-restored', 15),
      modifier('renard-greyfen-charter', -10),
      modifier('renard-denounced-central-rule', -8),
      modifier('renard-usurper', -10),
      modifier('renard-public-oathbreaker', -8),
    ],
    fear: { low: 0, concern: 2, serious: -5, existential: -15 },
    proofIds: [],
    redLineIds: [],
  },
] as const;

const shock = (
  id: string,
  value: number | null,
  expiresAfterDays: number | null,
  automatic: boolean,
  basisFilter: string[] = [],
  excludeBasisFilter: string[] = [],
) => ({
  id,
  value,
  expiresAfterDays,
  automatic,
  basisFilter,
  excludeBasisFilter,
  labelKey: label(`shock-${id}`),
  explanationKey: explanation(`shock-${id}`),
});

export const shocks = [
  shock('red-line-breach', null, null, true),
  shock('bargain-breach', null, null, true),
  shock('candidate-withdrawal', null, null, true),
  shock('coercive-leverage-lost', null, null, true, ['coercion']),
  shock('seat-occupied', 12, 10, false),
  shock('capital-lost', 12, 10, false),
  shock('major-defeat', 10, 10, false),
  shock('all-other-support-lost', 10, 10, false, ['opportunism']),
  shock('forgery-exposed', 20, 10, false, ['legitimacy']),
  shock('forgery-exposed-other-basis', 10, 10, false, [], ['legitimacy']),
  shock('renard-paternity-oswin', 15, 10, false),
  shock('renard-paternity-ysabel', 8, 10, false),
  shock('renard-foreign-concession-edric', 20, 10, false),
  shock('renard-testament-voluntary', 10, 10, false),
  shock('renard-testament-oswin', 15, 10, false),
  shock('edric-massacre-pledges', 10, 10, false),
  shock('ysabel-embezzlement-opportunism', 10, 10, false, ['opportunism']),
  shock('church-condemnation', 15, 10, false, ['legitimacy']),
  shock('public-oathbreaker', 10, 10, false),
];

export const churchStates = [
  {
    id: 'condemned',
    displayOrder: 0,
    caseMin: null,
    caseMax: null,
    labelKey: label('church-condemned'),
    explanationKey: explanation('church-condemned'),
  },
  {
    id: 'skeptical',
    displayOrder: 1,
    caseMin: 0,
    caseMax: 1,
    labelKey: label('church-skeptical'),
    explanationKey: explanation('church-skeptical'),
  },
  {
    id: 'neutral',
    displayOrder: 2,
    caseMin: 2,
    caseMax: 3,
    labelKey: label('church-neutral'),
    explanationKey: explanation('church-neutral'),
  },
  {
    id: 'favorable',
    displayOrder: 3,
    caseMin: 4,
    caseMax: 5,
    labelKey: label('church-favorable'),
    explanationKey: explanation('church-favorable'),
  },
  {
    id: 'endorsed',
    displayOrder: 4,
    caseMin: 6,
    caseMax: null,
    labelKey: label('church-endorsed'),
    explanationKey: explanation('church-endorsed'),
  },
] as const;

export const catalogs = {
  supportLevels: ['unaligned', 'leaning', 'pledged', 'committed', 'under-duress', 'self'].map(
    (id) => ({
      id,
      labelKey: label(`support-${id}`),
      explanationKey: explanation(`support-${id}`),
    }),
  ),
  supportBases: [
    'ideological',
    'legitimacy',
    'bargain',
    'opportunism',
    'protection',
    'coercion',
    'self',
  ].map((id) => ({
    id,
    labelKey: label(`support-basis-${id}`),
    explanationKey: explanation(`support-basis-${id}`),
  })),
  claimBands: [
    ['none', 0, 9],
    ['dubious', 10, 24],
    ['plausible', 25, 44],
    ['strong', 45, 64],
    ['excellent', 65, 84],
    ['overwhelming', 85, 100],
  ].map(([id, minimum, maximum]) => ({
    id,
    minimum,
    maximum,
    labelKey: label(`claim-${id}`),
    explanationKey: explanation(`claim-${id}`),
  })),
  prestigeBands: [
    {
      id: 'public-rating',
      minimum: 0,
      maximum: 100,
      labelKey: label('prestige-public-rating'),
      explanationKey: explanation('prestige-public-rating'),
    },
  ],
  offices: ['marshal', 'chancellor'].map((id) => ({
    id,
    labelKey: label(`office-${id}`),
    explanationKey: explanation(`office-${id}`),
  })),
  policies: [
    'greyfen-charter',
    'church-immunities',
    'denounce-central-rule',
    'provincial-liberties',
  ].map((id) => ({
    id,
    labelKey: label(`policy-${id}`),
    explanationKey: explanation(`policy-${id}`),
  })),
  conditions: [
    'tax-strain',
    'unrest',
    'occupied',
    'disgraced',
    'greyfen-charter',
    'provincial-liberties',
    'defaulted-debtor',
    'laughable-pretender',
    'oathbreaker',
    'usurper',
    'royally-sanctioned',
    'broke-kings-peace',
    'guard-favor',
    'ysabel-access-debt',
    'compromised-sovereignty',
    'forgery-evidence',
    'church-patronage',
    'oswin-simony',
    'debt-leverage',
  ].map((id) => ({
    id,
    labelKey: label(`condition-${id}`),
    explanationKey: explanation(`condition-${id}`),
  })),
  chronicleCategories: [
    'succession',
    'war',
    'court',
    'intelligence',
    'economy',
    'church',
    'system',
  ].map((id) => ({
    id,
    labelKey: label(`chronicle-${id}`),
    explanationKey: explanation(`chronicle-${id}`),
  })),
  explanationOrder: [
    'red-line',
    'binding-support',
    'proof-maturation',
    'desire-conduct',
    'bargain',
    'legitimacy',
    'viability',
    'fear',
    'relationship',
  ],
} as const;

export const constants = {
  clock: {
    crisisDays: 56,
    hoursPerDay: 24,
    realSecondsPerDayAtOneX: 60,
    deathDayWeights: {
      '49': 5,
      '50': 8,
      '51': 12,
      '52': 16,
      '53': 19,
      '54': 18,
      '55': 13,
      '56': 9,
    },
    prognosisReports: {
      '42': 'content.explanation.prognosis-day-42',
      '49': 'content.explanation.prognosis-day-49',
      '53': 'content.explanation.prognosis-day-53',
      '55': 'content.explanation.prognosis-day-55',
    },
    ambientWindows: [
      [6, 10],
      [14, 18],
      [22, 26],
      [30, 34],
      [38, 42],
      [45, 49],
    ],
    maxAmbientChoices: 6,
    maxChoiceInterruptionsPerDay: 1,
  },
  economy: {
    influencePerDawn: 1,
    influenceMaximum: 100,
    levyRecoveryRate: 0.005,
    occupationIncomeMultiplier: 0.25,
    taxStrainIncomeMultiplier: 0.5,
    taxStrainRecoveryMultiplier: 0.5,
    unrestIncomeMultiplier: 0.25,
    unrestRecoveryMultiplier: 0,
    greyfenCharterMultiplier: 0.75,
    provincialLibertiesMultiplier: 0.9,
    defaultedDebtorMultiplier: 0.5,
    churchImmunitiesTaxMultiplier: 0.8,
  },
  politics: {
    evaluation: {
      relationshipDivisor: 5,
      relationshipClamp: [-20, 20],
      bargainValues: { none: 0, offered: 8, accepted: 12, fulfilled: 20, sharedRisk: 25 },
      exactTieRetainsCurrentLeaning: true,
      noLeaningTieBreakOrder: ['relationship', 'legitimacy', 'declaration-time', 'candidate-id'],
    },
    hearBargainAt: 0,
    leanAt: 15,
    leanLead: 8,
    unalignBelow: 10,
    unalignLeadBelow: 4,
    defectionLead: 10,
    shockLifetimeDays: 10,
    requestPrematureCooldownDays: 7,
    publicCoercionEndorsementBlock: 2,
    officeReservationScope: 'per-candidate',
    accessDebt: {
      escrowGold: 100,
      chancellorshipGold: 60,
      protectionTroops: 150,
      consumedOnAcceptedBargain: true,
    },
    escrow: {
      supporterBreakReturnNow: 0.5,
      supporterBreakFrozenToDeath: 0.5,
      claimantBreakTransferToSupporter: 1,
      loyalAgreementLockedToSuccession: true,
    },
    viability: {
      modifiers: {
        'voluntary-pledge': 5,
        'voluntary-commitment': 8,
        'coerced-pledge-ysabel': 2,
        'coerced-pledge-edric': 0,
        'coerced-pledge-mara': 0,
        'coerced-pledge-oswin': -2,
        'claim-none': -8,
        'claim-dubious': -4,
        'claim-plausible': 0,
        'claim-strong': 3,
        'claim-excellent': 6,
        'claim-overwhelming': 8,
        'church-favorable': 3,
        'church-endorsed': 7,
        'capital-control': 5,
        'major-victory-recent': 4,
        'major-defeat-recent': -5,
        dispossessed: -6,
      },
      lordMultipliers: { greyfen: 1, edric: 1, ysabel: 1.25, renard: 1, oswin: 1, mara: 0.6 },
      clamp: [-20, 20],
    },
    relationshipChanges: {
      'gift-20': 4,
      'gift-40': 8,
      'gift-80': 12,
      'premature-request': -4,
      'externally-invalidated-request': -2,
      'break-agreement': -25,
      'public-threaten-target': -20,
      'occupy-seat': -40,
      'liberate-seat': 20,
      'expose-secret': -30,
      'join-defensive-war': 12,
      'first-court-invitee': 6,
      'diminished-court-invitee': 3,
      'first-patronage-oswin': 8,
      'later-patronage-oswin': 3,
      'abbey-endowment-oswin': 8,
    },
    coercion: {
      militaryThresholds: {
        greyfen: null,
        edric: 2,
        ysabel: 1.25,
        renard: null,
        oswin: null,
        mara: 1.5,
      },
      edricOccupationArmyBelow: 250,
      secretBlackmailUseLimit: 1,
      publicThreatTargetRelationship: -20,
      publicThreatObserverRelationship: -5,
    },
    candidacy: {
      renardAutomaticPhase: 'ailing',
      playerMinimumPhase: 'ailing',
      edricMinimumPhase: 'gravely-ill',
      edricMaximumRenardSupporters: 1,
      edricMinimumTroops: 500,
      edricMinimumPrestige: 50,
      edricRequiresNoValidPledge: true,
      renardWithdrawalMaximumSupporters: 0,
      renardWithdrawalMilitaryBelow: 150,
      renardWithdrawalRequiresCapitalLeverage: true,
    },
  },
  church: {
    endorsementCaseMinimum: 6,
    minimumClaimBand: 'plausible',
    oneEndorsedMaximum: 1,
    claimCase: { none: 0, dubious: 1, plausible: 2, strong: 3, excellent: 4, overwhelming: 5 },
    modifiers: {
      'oswin-pledged': 2,
      'oswin-committed': 4,
      'oswin-pledged-after-simony': 1,
      'oswin-committed-after-simony': 2,
      patronage: 1,
      'renard-undiscredited-favorite': 1,
      'defended-abbeylands': 1,
      funeral: 1,
      usurper: -2,
      'broke-peace': -1,
      'stable-defiance-additional': -1,
    },
  },
  war: {
    hereditaryGarrison: 75,
    capitalGarrison: 200,
    capitalAttackMinimum: 250,
    campaignDays: 3,
    deathbedCampaignDays: 2,
    campaignLogisticsGold: 10,
    aiYieldRatio: 1.75,
    mercenaryBandSize: 150,
    mercenaryInitialGold: 50,
    maraMercenaryInitialGold: 40,
    mercenaryRenewalGold: 20,
    mercenaryContractDays: 7,
    mercenaryMaximumBands: 2,
    commanderOrdinary: 1,
    commanderEdric: 1.1,
    fortuneMin: 0.92,
    fortuneMax: 1.08,
    fortificationStep: 0.1,
    majorBattleTroops: 250,
    casualty: {
      loserBase: 0.28,
      loserRatioStep: 0.08,
      loserMin: 0.28,
      loserMax: 0.45,
      winnerBase: 0.18,
      winnerRatioStep: 0.04,
      winnerMin: 0.08,
      winnerMax: 0.18,
    },
    threatBands: { concern: 20, serious: 40, existential: 60 },
    threatValues: {
      militarySuperior: 20,
      adjacentOccupation: 15,
      occupiedSeat: 10,
      capitalControl: 15,
      twoPublicSupporters: 10,
      secondOffensiveWar: 10,
      publiclyKnownCoercedPledge: 10,
      voluntaryCommitmentReduction: -10,
      militaryComparisonRatio: 1.25,
    },
    armyBandMidpoints: { broken: 75, modest: 225, strong: 400, formidable: 600 },
  },
  succession: {
    councilVotes: 6,
    majority: 4,
    acclamationNonCapitalSeats: 3,
    acclamationCapitalTroops: 200,
    eliminationTieBreakOrder: ['commitments', 'claim', 'prestige', 'declaration-time'],
    finalTieBreakOrder: [
      'church-endorsement',
      'capital-control',
      'commitments',
      'claim',
      'prestige',
      'declaration-time',
    ],
  },
  spy: {
    base: 50,
    influenceDivisor: 5,
    seededMinimum: -15,
    seededMaximum: 15,
    cleanSuccessMargin: 10,
    detectionAtSuccessPercent: 25,
    partialMargin: -10,
    detectionAtPartialPercent: 50,
    repeatWindowDays: 10,
    repeatDetectionIncreasePercent: 20,
    detectionMaximumPercent: 100,
  },
  claimFraud: {
    researchClaim: 12,
    forgeClaim: 25,
    exposureClaimLoss: 20,
    exposurePrestigeLoss: 10,
    rumorConfessionClaimLoss: 12,
    rumorConfessionPrestigeLoss: 5,
    penanceGold: 40,
    penanceInfluence: 10,
    penanceDays: 3,
    penancePrestigeLoss: 5,
  },
  prestigeChanges: {
    'declare-none': -5,
    'declare-plausible': 3,
    'declare-strong-or-better': 5,
    'major-victory': 8,
    'minor-victory': 4,
    'lose-major-attack': -6,
    'lose-major-defense': -4,
    yield: -5,
    'capital-victory': 8,
    'capital-loss': -8,
    dispossessed: -8,
    'hold-court': 8,
    'break-agreement': -8,
    'loan-default': -12,
    'forgery-exposed': -10,
    penance: -5,
  },
  royalAuthority: {
    stable: {
      additionalInfluence: 15,
      prestige: -10,
      churchConduct: -1,
      nonBelligerentRelationship: -8,
      maraRelationship: -2,
      royalReinforcement: 150,
      capitalAttackAllowed: false,
    },
    ailing: {
      additionalInfluence: 0,
      prestige: -5,
      churchConduct: 0,
      nonBelligerentRelationship: 0,
      maraRelationship: 0,
      royalReinforcement: 0,
      capitalAttackAllowed: false,
    },
    'gravely-ill': {
      additionalInfluence: 0,
      prestige: 0,
      churchConduct: 0,
      nonBelligerentRelationship: 0,
      maraRelationship: 0,
      royalReinforcement: 0,
      capitalAttackAllowed: true,
    },
    deathbed: {
      additionalInfluence: 0,
      prestige: 0,
      churchConduct: 0,
      nonBelligerentRelationship: 0,
      maraRelationship: 0,
      royalReinforcement: 0,
      capitalAttackAllowed: true,
    },
  },
  routeBudgets: {
    coalitionMinimumInfluence: 63,
    coalitionBargains: 3,
    coalitionRequests: 3,
    militaryMinimumGarrisons: 350,
  },
  tuningInvariantIds: [
    'future-promise-never-pledges-alone',
    'three-kingmakers-exceed-starting-stockpile',
    'claim-oswin-route-no-event-luck',
    'one-battle-no-normal-acclamation',
    'two-occupations-capital-exceed-starting-levies',
    'mercenary-conquest-possible',
    'repeated-taxes-worsen',
    'late-declaration-cannot-mature-several-pledges',
    'renard-favored-not-automatic',
    'decisive-number-previewed-or-reconstructible',
  ],
} as const;
