import type { StructuredEffect } from './schemas';

const label = (id: string) => `content.label.${id}`;
const explanation = (id: string) => `content.explanation.${id}`;

const effect = (
  effectId: StructuredEffect['effectId'],
  target: StructuredEffect['target'],
  value?: number,
  referenceId?: string,
): StructuredEffect => ({
  effectId,
  target,
  ...(value === undefined ? {} : { value }),
  ...(referenceId === undefined ? {} : { referenceId }),
  visibility: 'public',
});

export const phases = [
  {
    id: 'stable',
    displayOrder: 1,
    labelKey: label('phase-stable'),
    explanationKey: explanation('phase-stable'),
    remainingDayMin: 43,
    remainingDayMax: 56,
    maturationDays: 0,
    pledgeInertia: 0,
    capitalGarrison: null,
    canDeclare: false,
    canRequestPledge: false,
    canAttackCapital: false,
    longPreparationsLocked: false,
    shortActionReductionDays: 0,
  },
  {
    id: 'ailing',
    displayOrder: 2,
    labelKey: label('phase-ailing'),
    explanationKey: explanation('phase-ailing'),
    remainingDayMin: 29,
    remainingDayMax: 42,
    maturationDays: 2,
    pledgeInertia: 10,
    capitalGarrison: null,
    canDeclare: true,
    canRequestPledge: true,
    canAttackCapital: false,
    longPreparationsLocked: false,
    shortActionReductionDays: 0,
  },
  {
    id: 'gravely-ill',
    displayOrder: 3,
    labelKey: label('phase-gravely-ill'),
    explanationKey: explanation('phase-gravely-ill'),
    remainingDayMin: 15,
    remainingDayMax: 28,
    maturationDays: 3,
    pledgeInertia: 20,
    capitalGarrison: 450,
    canDeclare: true,
    canRequestPledge: true,
    canAttackCapital: true,
    longPreparationsLocked: false,
    shortActionReductionDays: 0,
  },
  {
    id: 'deathbed',
    displayOrder: 4,
    labelKey: label('phase-deathbed'),
    explanationKey: explanation('phase-deathbed'),
    remainingDayMin: 0,
    remainingDayMax: 14,
    maturationDays: 4,
    pledgeInertia: 30,
    capitalGarrison: 300,
    canDeclare: true,
    canRequestPledge: true,
    canAttackCapital: true,
    longPreparationsLocked: true,
    shortActionReductionDays: 1,
  },
] as const;

export const territories = [
  {
    id: 'greyfen',
    displayOrder: 1,
    labelKey: label('territory-greyfen'),
    explanationKey: explanation('territory-greyfen'),
    legalLordId: 'greyfen',
    adjacentTerritoryIds: ['westmarch', 'capital', 'abbeylands'],
    wealth: 2,
    levyCapacity: 420,
    startingLevies: 360,
    fortification: 1,
    traitId: 'fen-roads',
    traitKey: label('trait-fen-roads'),
    traitParameters: { 'adjacent-watch-court-gold-discount': 5 },
    legalIncomeBonus: 0,
    occupierIncomePerDay: 0.5,
  },
  {
    id: 'northkeep',
    displayOrder: 2,
    labelKey: label('territory-northkeep'),
    explanationKey: explanation('territory-northkeep'),
    legalLordId: 'edric',
    adjacentTerritoryIds: ['westmarch', 'capital', 'eastvale'],
    wealth: 2,
    levyCapacity: 720,
    startingLevies: 620,
    fortification: 3,
    traitId: 'iron-hills',
    traitKey: label('trait-iron-hills'),
    traitParameters: { 'edric-defender-power-multiplier': 1.1 },
    legalIncomeBonus: 0,
    occupierIncomePerDay: 0.5,
  },
  {
    id: 'westmarch',
    displayOrder: 3,
    labelKey: label('territory-westmarch'),
    explanationKey: explanation('territory-westmarch'),
    legalLordId: 'mara',
    adjacentTerritoryIds: ['northkeep', 'capital', 'greyfen'],
    wealth: 2,
    levyCapacity: 500,
    startingLevies: 430,
    fortification: 1,
    traitId: 'free-companies',
    traitKey: label('trait-free-companies'),
    traitParameters: { 'mara-mercenary-initial-gold': 40, 'occupier-gains-trait': false },
    legalIncomeBonus: 0,
    occupierIncomePerDay: 0.5,
  },
  {
    id: 'eastvale',
    displayOrder: 4,
    labelKey: label('territory-eastvale'),
    explanationKey: explanation('territory-eastvale'),
    legalLordId: 'ysabel',
    adjacentTerritoryIds: ['northkeep', 'capital', 'southmere'],
    wealth: 5,
    levyCapacity: 300,
    startingLevies: 240,
    fortification: 1,
    traitId: 'golden-vale',
    traitKey: label('trait-golden-vale'),
    traitParameters: { 'legal-physical-controller-gold-per-day': 1 },
    legalIncomeBonus: 1,
    occupierIncomePerDay: 1.25,
  },
  {
    id: 'abbeylands',
    displayOrder: 5,
    labelKey: label('territory-abbeylands'),
    explanationKey: explanation('territory-abbeylands'),
    legalLordId: 'oswin',
    adjacentTerritoryIds: ['greyfen', 'capital', 'southmere'],
    wealth: 3,
    levyCapacity: 260,
    startingLevies: 210,
    fortification: 2,
    traitId: 'holy-seat',
    traitKey: label('trait-holy-seat'),
    traitParameters: { 'unjustified-violence-extra-church-penalty': 1 },
    legalIncomeBonus: 0,
    occupierIncomePerDay: 0.75,
  },
  {
    id: 'southmere',
    displayOrder: 6,
    labelKey: label('territory-southmere'),
    explanationKey: explanation('territory-southmere'),
    legalLordId: 'renard',
    adjacentTerritoryIds: ['eastvale', 'capital', 'abbeylands'],
    wealth: 4,
    levyCapacity: 520,
    startingLevies: 450,
    fortification: 2,
    traitId: 'old-blood',
    traitKey: label('trait-old-blood'),
    traitParameters: { 'occupier-gains-claim': false },
    legalIncomeBonus: 0,
    occupierIncomePerDay: 1,
  },
  {
    id: 'capital',
    displayOrder: 7,
    labelKey: label('territory-capital'),
    explanationKey: explanation('territory-capital'),
    legalLordId: null,
    adjacentTerritoryIds: [
      'greyfen',
      'northkeep',
      'westmarch',
      'eastvale',
      'abbeylands',
      'southmere',
    ],
    wealth: 4,
    levyCapacity: null,
    startingLevies: null,
    fortification: 3,
    traitId: 'seat-of-crown',
    traitKey: label('trait-seat-of-crown'),
    traitParameters: { 'tie-break-only': true, 'military-acclamation-gate': true },
    legalIncomeBonus: 0,
    occupierIncomePerDay: 1,
  },
] as const;

export const lords = [
  {
    id: 'greyfen',
    displayOrder: 1,
    labelKey: label('lord-greyfen'),
    explanationKey: explanation('lord-greyfen'),
    titleKey: label('title-lord-of-greyfen'),
    epithetKey: label('epithet-petty-lord'),
    seatId: 'greyfen',
    isPlayer: true,
    mayDeclare: true,
    startsDeclared: false,
    starting: {
      gold: 70,
      availableLevies: 360,
      levyCapacity: 420,
      prestige: 12,
      claim: 10,
      influence: 35,
    },
    desireKey: explanation('desire-greyfen'),
    fearKey: explanation('fear-greyfen'),
    proofIds: [],
    redLineIds: [],
    specialAdvantageId: 'two-orders',
    aiPersonality: { tags: ['player-controlled'], weights: { politics: 0 } },
    candidacyRuleId: 'player-declare-from-ailing',
    bargainIds: [],
    initialSupport: { candidateId: null, level: 'unaligned', basis: null, visibility: 'private' },
  },
  {
    id: 'edric',
    displayOrder: 2,
    labelKey: label('lord-edric'),
    explanationKey: explanation('lord-edric'),
    titleKey: label('title-lord-of-northkeep'),
    epithetKey: label('epithet-hawk'),
    seatId: 'northkeep',
    isPlayer: false,
    mayDeclare: true,
    startsDeclared: false,
    starting: {
      gold: 55,
      availableLevies: 620,
      levyCapacity: 720,
      prestige: 55,
      claim: 18,
      influence: 35,
    },
    desireKey: explanation('desire-edric'),
    fearKey: explanation('fear-edric'),
    proofIds: [
      'edric-major-victory',
      'edric-military-peer',
      'edric-border-aid',
      'edric-capital-control',
    ],
    redLineIds: [
      'edric-broke-promised-aid',
      'edric-abandoned-shared-war',
      'edric-northkeep-occupied',
      'edric-destruction-program',
    ],
    specialAdvantageId: 'veteran-command',
    aiPersonality: {
      tags: ['military', 'honor', 'conditional-claimant'],
      weights: { defense: 100, military: 20, politics: 5, legitimacy: -5 },
    },
    candidacyRuleId: 'edric-gravely-conditions',
    bargainIds: ['edric-marshal', 'edric-border-aid', 'edric-joint-campaign'],
    initialSupport: { candidateId: null, level: 'unaligned', basis: null, visibility: 'private' },
  },
  {
    id: 'ysabel',
    displayOrder: 3,
    labelKey: label('lord-ysabel'),
    explanationKey: explanation('lord-ysabel'),
    titleKey: label('title-lady-of-eastvale'),
    epithetKey: label('epithet-spider'),
    seatId: 'eastvale',
    isPlayer: false,
    mayDeclare: false,
    startsDeclared: false,
    starting: {
      gold: 170,
      availableLevies: 240,
      levyCapacity: 300,
      prestige: 36,
      claim: 24,
      influence: 55,
    },
    desireKey: explanation('desire-ysabel'),
    fearKey: explanation('fear-ysabel'),
    proofIds: [
      'ysabel-public-support',
      'ysabel-claim-and-church',
      'ysabel-capital-control',
      'ysabel-rival-defeat',
      'ysabel-escrow',
      'ysabel-protection',
    ],
    redLineIds: [
      'ysabel-eastvale-occupied',
      'ysabel-defaulted-debtor',
      'ysabel-network-destroyed',
      'ysabel-bargain-collapse',
    ],
    specialAdvantageId: 'web-of-credit',
    aiPersonality: {
      tags: ['wealth', 'kingmaker', 'opportunist'],
      weights: { defense: 100, economy: 20, politics: 18, protection: 15 },
    },
    candidacyRuleId: 'never-declares',
    bargainIds: ['ysabel-escrow', 'ysabel-chancellorship', 'ysabel-protection'],
    initialSupport: {
      candidateId: 'renard',
      level: 'leaning',
      basis: 'opportunism',
      visibility: 'private',
    },
  },
  {
    id: 'renard',
    displayOrder: 4,
    labelKey: label('lord-renard'),
    explanationKey: explanation('lord-renard'),
    titleKey: label('title-lord-of-southmere'),
    epithetKey: label('epithet-favorite'),
    seatId: 'southmere',
    isPlayer: false,
    mayDeclare: true,
    startsDeclared: false,
    starting: {
      gold: 110,
      availableLevies: 450,
      levyCapacity: 520,
      prestige: 48,
      claim: 72,
      influence: 60,
    },
    desireKey: explanation('desire-renard'),
    fearKey: explanation('fear-renard'),
    proofIds: [],
    redLineIds: [],
    specialAdvantageId: 'royal-favorite',
    aiPersonality: {
      tags: ['principal-claimant', 'legitimacy', 'containment'],
      weights: { defense: 100, legitimacy: 20, politics: 18, containment: 15 },
    },
    candidacyRuleId: 'automatic-at-ailing',
    bargainIds: [],
    initialSupport: { candidateId: null, level: 'unaligned', basis: null, visibility: 'private' },
  },
  {
    id: 'oswin',
    displayOrder: 5,
    labelKey: label('lord-oswin'),
    explanationKey: explanation('lord-oswin'),
    titleKey: label('title-lord-of-abbeylands'),
    epithetKey: label('epithet-pious'),
    seatId: 'abbeylands',
    isPlayer: false,
    mayDeclare: false,
    startsDeclared: false,
    starting: {
      gold: 85,
      availableLevies: 210,
      levyCapacity: 260,
      prestige: 42,
      claim: 16,
      influence: 50,
    },
    desireKey: explanation('desire-oswin'),
    fearKey: explanation('fear-oswin'),
    proofIds: ['oswin-lawful-legitimacy'],
    redLineIds: [
      'oswin-abbeylands-attacked',
      'oswin-unconfessed-forgery',
      'oswin-church-wealth-seized',
      'oswin-sacrilegious-agreement',
      'oswin-public-coercion',
    ],
    specialAdvantageId: 'voice-of-synod',
    aiPersonality: {
      tags: ['church', 'lawful', 'kingmaker'],
      weights: { defense: 100, church: 20, legitimacy: 18, coercion: -20 },
    },
    candidacyRuleId: 'never-declares',
    bargainIds: ['oswin-abbey-endowment', 'oswin-church-immunities', 'oswin-renunciation'],
    initialSupport: {
      candidateId: 'renard',
      level: 'leaning',
      basis: 'legitimacy',
      visibility: 'private',
    },
  },
  {
    id: 'mara',
    displayOrder: 6,
    labelKey: label('lord-mara'),
    explanationKey: explanation('lord-mara'),
    titleKey: label('title-lady-of-westmarch'),
    epithetKey: label('epithet-rebel'),
    seatId: 'westmarch',
    isPlayer: false,
    mayDeclare: false,
    startsDeclared: false,
    starting: {
      gold: 65,
      availableLevies: 430,
      levyCapacity: 500,
      prestige: 34,
      claim: 12,
      influence: 40,
    },
    desireKey: explanation('desire-mara'),
    fearKey: explanation('fear-mara'),
    proofIds: ['mara-charter', 'mara-provincial-aid', 'mara-liberation'],
    redLineIds: [
      'mara-westmarch-occupied',
      'mara-charter-revoked',
      'mara-centralizing-program',
      'mara-provincial-aid-betrayed',
    ],
    specialAdvantageId: 'march-liberties',
    aiPersonality: {
      tags: ['anti-centralist', 'kingmaker', 'mercenary'],
      weights: { defense: 100, autonomy: 20, 'anti-crown': 15, conquest: -15 },
    },
    candidacyRuleId: 'never-declares',
    bargainIds: ['mara-greyfen-charter', 'mara-denounce-central-rule', 'mara-provincial-aid'],
    initialSupport: { candidateId: null, level: 'unaligned', basis: null, visibility: 'private' },
  },
] as const;

export const relationships = [
  ['greyfen', 'edric', 0],
  ['greyfen', 'ysabel', 5],
  ['greyfen', 'renard', -10],
  ['greyfen', 'oswin', 0],
  ['greyfen', 'mara', 10],
  ['edric', 'ysabel', 5],
  ['edric', 'renard', -20],
  ['edric', 'oswin', 10],
  ['edric', 'mara', -20],
  ['ysabel', 'renard', 20],
  ['ysabel', 'oswin', 5],
  ['ysabel', 'mara', 0],
  ['renard', 'oswin', 15],
  ['renard', 'mara', -30],
  ['oswin', 'mara', -10],
].map(([firstLordId, secondLordId, value]) => ({ firstLordId, secondLordId, value }));

const proof = (id: string, lordId: string, ruleId: string) => ({
  id,
  lordId,
  ruleId,
  labelKey: label(`proof-${id}`),
  explanationKey: explanation(`proof-${id}`),
});

export const proofs = [
  proof('edric-major-victory', 'edric', 'major-battle-won-within-14-days'),
  proof('edric-military-peer', 'edric', 'known-effective-military-90-percent-and-prestige-35'),
  proof('edric-border-aid', 'edric', 'fulfilled-border-aid-or-joint-obligation'),
  proof('edric-capital-control', 'edric', 'capital-held-three-days-without-major-defeat'),
  proof('ysabel-public-support', 'ysabel', 'another-voluntary-public-supporter'),
  proof('ysabel-claim-and-church', 'ysabel', 'plausible-claim-and-favorable-church'),
  proof('ysabel-capital-control', 'ysabel', 'capital-controlled'),
  proof('ysabel-rival-defeat', 'ysabel', 'rival-claimant-defeated-in-major-battle'),
  proof('ysabel-escrow', 'ysabel', 'accepted-escrow-at-least-80'),
  proof('ysabel-protection', 'ysabel', 'accepted-protection-at-least-100'),
  proof('oswin-lawful-legitimacy', 'oswin', 'plausible-claim-plus-lawful-church-proof'),
  proof('mara-charter', 'mara', 'greyfen-charter-enacted'),
  proof('mara-provincial-aid', 'mara', 'provincial-aid-fulfilled'),
  proof('mara-liberation', 'mara', 'westmarch-liberated'),
];

const redLine = (id: string, lordId: string, automaticBreaker = true) => ({
  id,
  lordId,
  automaticBreaker,
  ruleId: id,
  labelKey: label(`red-line-${id}`),
  explanationKey: explanation(`red-line-${id}`),
});

export const redLines = [
  redLine('edric-broke-promised-aid', 'edric'),
  redLine('edric-abandoned-shared-war', 'edric'),
  redLine('edric-northkeep-occupied', 'edric'),
  redLine('edric-destruction-program', 'edric'),
  redLine('ysabel-eastvale-occupied', 'ysabel'),
  redLine('ysabel-defaulted-debtor', 'ysabel'),
  redLine('ysabel-network-destroyed', 'ysabel'),
  redLine('ysabel-bargain-collapse', 'ysabel'),
  redLine('oswin-abbeylands-attacked', 'oswin'),
  redLine('oswin-unconfessed-forgery', 'oswin'),
  redLine('oswin-church-wealth-seized', 'oswin'),
  redLine('oswin-sacrilegious-agreement', 'oswin'),
  redLine('oswin-public-coercion', 'oswin'),
  redLine('mara-westmarch-occupied', 'mara'),
  redLine('mara-charter-revoked', 'mara'),
  redLine('mara-centralizing-program', 'mara'),
  redLine('mara-provincial-aid-betrayed', 'mara'),
];

const renardSecretPool = [
  'renard-questioned-paternity',
  'renard-foreign-concession',
  'renard-bought-royal-testament',
] as const;

const additionalSecretPool = [
  'edric-border-massacre',
  'ysabel-tax-embezzlement',
  'oswin-simony',
  'mara-smuggler-compact',
] as const;

export const openings = [
  {
    id: 'fractured-court',
    displayOrder: 1,
    labelKey: label('opening-fractured-court'),
    explanationKey: explanation('opening-fractured-court'),
    compatibilityRouteIds: ['coalition', 'legitimacy', 'intrigue', 'military'],
    effects: [
      effect('adjust-relationship', 'ysabel', -10, 'renard'),
      effect('adjust-prestige', 'edric', 5),
      effect('adjust-relationship', 'mara', 5, 'greyfen'),
    ],
    guaranteedSecretTargetId: 'renard',
    guaranteedSecretPool: renardSecretPool,
    additionalSecretPool,
    additionalSecretCount: 2,
  },
  {
    id: 'border-crisis',
    displayOrder: 2,
    labelKey: label('opening-border-crisis'),
    explanationKey: explanation('opening-border-crisis'),
    compatibilityRouteIds: ['coalition', 'intrigue', 'military'],
    effects: [
      effect('adjust-levies', 'edric', -60),
      effect('adjust-levies', 'mara', -60),
      effect('adjust-relationship', 'mara', -10, 'edric'),
      effect('set-intent-weight', 'edric', 1, 'border'),
      effect('set-intent-weight', 'mara', 1, 'border'),
    ],
    guaranteedSecretTargetId: 'renard',
    guaranteedSecretPool: renardSecretPool,
    additionalSecretPool,
    additionalSecretCount: 2,
  },
  {
    id: 'holy-anxiety',
    displayOrder: 3,
    labelKey: label('opening-holy-anxiety'),
    explanationKey: explanation('opening-holy-anxiety'),
    compatibilityRouteIds: ['coalition', 'legitimacy', 'intrigue'],
    effects: [
      effect('adjust-church-conduct', 'renard', -2),
      effect('adjust-gold', 'oswin', 15),
      effect('adjust-levies', 'oswin', -30),
      effect('set-intent-weight', 'oswin', 1, 'investigate-legitimacy'),
    ],
    guaranteedSecretTargetId: 'renard',
    guaranteedSecretPool: renardSecretPool,
    additionalSecretPool,
    additionalSecretCount: 2,
  },
  {
    id: 'favorite-ascendant',
    displayOrder: 4,
    labelKey: label('opening-favorite-ascendant'),
    explanationKey: explanation('opening-favorite-ascendant'),
    compatibilityRouteIds: ['coalition', 'intrigue', 'military'],
    effects: [
      effect('set-bargain-progress', 'ysabel', 1, 'renard'),
      effect('adjust-gold', 'ysabel', 20),
      effect('set-intent-weight', 'renard', 1, 'request-ysabel-at-ailing'),
    ],
    guaranteedSecretTargetId: 'renard',
    guaranteedSecretPool: renardSecretPool,
    additionalSecretPool,
    additionalSecretCount: 2,
  },
] as const;
